# site name
prefixName: 最菜の
siteName: louhc
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/custom/avatar.jpg
url: https://louhc.github.io
description: Live your life with passion! With some drive!
cdn: https://cdn.jsdelivr.net/gh/louhc/cdn@latest
pjax: 1
# 1开启
mathjax: 1

notice: louhc's blog. qwq
lazyloadImg: https://cdn.jsdelivr.net/gh/louhc/cdn@latest/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: {
    题解: {path: /categories/题解/, fa: fa-code },
    算法: {path: //akari-oi.github.io, fa: fa-code },
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book },
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    番剧: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo },
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce } 
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/0.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/1.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/2.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/3.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/4.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/5.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/6.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/7.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/8.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/9.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/10.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/11.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/12.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/13.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/14.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/15.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/16.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/17.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/18.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/19.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/20.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/21.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/22.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/23.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/24.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/25.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/26.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/27.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/28.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/29.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/30.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/31.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/32.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/33.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/34.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/35.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/36.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/37.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/38.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/39.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/40.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/41.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/42.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/43.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/44.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/45.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/46.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/47.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/48.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/49.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/50.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/51.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/52.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/53.jpg
  - https://cdn.jsdelivr.net/gh/louhc/cdn@1.1/img/cover/54.jpg


# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /, title: louhc, desc: 还不知道该放啥, img: /img/startdash/sakura.md.png}
  - {url: https://space.bilibili.com/360170221, title: bilibili, desc: 博主的b站主页, img: /img/startdash/bilibili.jpg}
  - {url: /, title: louhc, desc: 还不知道该放啥, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 01/8/2019

#social  url, img PC端配置
social:
  github: {url: http://github.com/Louhc, img: /img/social/github.png}
  sina: {url: https://weibo.com/u/7270709586, img: /img/social/sina.png}
  wangyiyun: {url: https://music.163.com/#/user/home?id=1744517357, img: /img/social/wangyiyun.png}
  zhihu: {url: https://www.zhihu.com/people/louhc/activities, img: /img/social/zhihu.png}
  email: {url: 1098766736@qq.com, img: /img/social/email.svg}
  wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/louhc, fa: fa-github, color: 333}
  weibo: {url: https://weibo.com/u/7270709586, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=1098766736&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  paypal: https://www.paypal.me/louhc
  alipay: /img/custom/donate/AliPayQR.jpg
  wechat: /img/custom/donate/WeChanQR.jpg
  wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/louhc/cdn@1.1
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: dalabengba.mp4

aplayer: 
  id: 2912437347
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: fsQVO1X0eIJHcp0HPluTWvl1-gzGzoHsz
v_appKey: zi5uU2gcU5Ng8x2WSb2JIWdo

